framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    assets:
        packages:
            cdn_nocache_insecure:
                base_urls:
                    - 'http://cdn-%env(APP_BASE_URL)%'
            cdn_nocache_secure:
                base_urls:
                    - 'https://cdn-%env(APP_BASE_URL)%'
            cdn_cache_insecure:
                version_format: '%%s?cache_assets=true'
                version: '1'
                base_urls:
                    - 'http://cdn-%env(APP_BASE_URL)%'
            cdn_cache_secure:
                version_format: '%%s?cache_assets=true'
                version: '1'
                base_urls:
                    - 'https://cdn-%env(APP_BASE_URL)%'
            thirdparty:
                base_urls:
                    - 'https://%env(THIRD_PARTY_BASE_URL)%'
            relative:
                base_path: '/images'
            js:
                base_path: '/js'
