version: "3.2"
services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
  php:
    image: kraynel/catbook_php:latest-slow
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www:cached
  php-fast:
    image: kraynel/catbook_php:latest-fast
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        PROD_OPTIM: "true"
    environment:
      APP_DEBUG: 0
    volumes:
      - ./:/var/www:cached
  nginx:
    image: kraynel/catbook_nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "444:444"
    volumes:
      - ./public:/var/www/public:cached,ro
      - ./docker/nginx/certs:/etc/letsencrypt:cached,ro